Enforce super user

diff --git a/bin/radio-etiopia b/bin/radio-etiopia
--- a/bin/radio-etiopia
+++ b/bin/radio-etiopia
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 set -Eeuo pipefail
 
+if ((EUID != 0)); then
+    echo 'Super-user privileges are required to run Docker on Synology.' >&2
+    exit 1
+fi
+
 # Go to the root directory where the docker-compose.yaml file resides.
 cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")"
 
diff --git a/bin/rtorrent-down b/bin/rtorrent-down
--- a/bin/rtorrent-down
+++ b/bin/rtorrent-down
@@ -1,2 +1,9 @@
-#!/bin/sh
+#!/usr/bin/env bash
+set -Eeuo pipefail
+
+if ((EUID != 0)); then
+    echo 'Super-user privileges are required to run Docker on Synology.' >&2
+    exit 1
+fi
+
 exec docker-compose --project-name rtorrent down
diff --git a/bin/rtorrent-up b/bin/rtorrent-up
--- a/bin/rtorrent-up
+++ b/bin/rtorrent-up
@@ -1,6 +1,14 @@
-#!/bin/sh
+#!/usr/bin/env bash
+set -Eeuo pipefail
+
+if ((EUID != 0)); then
+    echo 'Super-user privileges are required to run Docker on Synology.' >&2
+    exit 1
+fi
+
 DOCKER_UID=$(id -u Richard)
 DOCKER_GID=$(id -g Richard)
 FLOOD_SECRET=$(openssl rand -hex 40)
 export DOCKER_UID DOCKER_GID FLOOD_SECRET
+
 exec docker-compose --project-name rtorrent up --detach rtorrent rtorrent-flood
